# Generated by Django 5.0.8 on 2024-10-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anon", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="encrypted_content",
        ),
        migrations.AddField(
            model_name="message",
            name="content",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="PlainTextMessage",
        ),
    ]
