# Generated by Django 4.0 on 2024-05-08 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anon', '0002_publickeydirectory_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encryptionkey',
            old_name='key_value',
            new_name='private_key',
        ),
    ]
