# Generated by Django 5.0.6 on 2024-05-11 16:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anon', '0003_rename_key_value_encryptionkey_private_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlainTextMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_plain_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_plain_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'plain_text_messages',
            },
        ),
    ]
