# Generated by Django 5.0.8 on 2024-10-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anon", "0005_alter_conversation_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="user_pins",
            field=models.JSONField(default=dict),
        ),
    ]
