# Generated by Django 5.0.6 on 2024-05-12 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anon', '0005_alter_encryptionkey_private_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='encrypted_session_key',
        ),
    ]
