# Generated by Django 5.0.6 on 2024-05-12 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anon', '0006_remove_message_encrypted_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptionkey',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='private_key', to=settings.AUTH_USER_MODEL),
        ),
    ]
