# Generated by Django 5.0.8 on 2024-11-14 12:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("anon", "0007_alter_conversation_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainuser",
            name="profile_pic",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
