GET http://127.0.0.1:8000/messages/5f940619-a497-479b-8529-8dc392433a80/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE2MTAxMzM4LCJpYXQiOjE3MTU0OTY1MzgsImp0aSI6IjI5NGFiZjI3OWM2MDQ3OWE4NzFlY2E5OTRkMzMyNDFjIiwidXNlcl9pZCI6ImNlZjM0ZjdjLTIwNGItNDE2Yy04Mzk3LWE3Yzk0ZGZmZDEzNCJ9.TXFi19XIxb-IB_0uWfZgMPSw80xgisxWbvBOKuAPhwY