GET http://127.0.0.1:8000/messages/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE2MDU4MTA0LCJpYXQiOjE3MTU0NTMzMDQsImp0aSI6IjdjMmM0YzcxN2NiNTQ2NzA4NmJjYThjMmQwZDU1MDhhIiwidXNlcl9pZCI6ImUwMjc4NmU4LTBmN2YtNDg5NC05MzRmLTMyNWFmZmZjNDQzOCJ9.b3qxpyI8qbETtT9D8OBLknHyNDcXcrhLhKSl28uWawg