GET http://127.0.0.1:8000/profile/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE1OTY3NDIxLCJpYXQiOjE3MTUzNjI2MjEsImp0aSI6ImI3OGE4Zjc0ZmMzZjQ3NWRhMWIxMDIyMTRkYzJiYThhIiwidXNlcl9pZCI6ImUwMjc4NmU4LTBmN2YtNDg5NC05MzRmLTMyNWFmZmZjNDQzOCJ9.SWCUezGhp4u2vi5hiwxy1lJ4cCbnEXt7w4fE8ODBqMM