POST http://127.0.0.1:8000/send-message/cef34f7c-204b-416c-8397-a7c94dffd134/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE2MTA5MTEzLCJpYXQiOjE3MTU1MDQzMTMsImp0aSI6IjVhNGZlNjgwN2IxNjRlZjg5OGY5YjQ5MTg4OTdkYzBjIiwidXNlcl9pZCI6IjVmOTQwNjE5LWE0OTctNDc5Yi04NTI5LThkYzM5MjQzM2E4MCJ9.6hWoaGTHBjonsexXmzmDAOQNz68ANRukuaAn1-p_Cj0

{
    "content": "Got your message idanmhiiii"
}